In [ ]:
pip install opencv-python

In [2]:
import cv2
import matplotlib.pyplot as plt

In [11]:
cv2.__version__

'4.6.0'

In [3]:
img = cv2.imread('4.png')
#img

<b>1- filename</b> is the first and the compulsory parameter to be passed and it takes a string value representing the path of the image file (or the image name with extension). NOTE: We have to pass the full path of the image file if is not in the working directory.<br>
<b>2- flag </b>is the second and the optional parameter to be passed and it usually takes three types of values: cv2.IMREAD_COLOR, cv2.IMREAD_GRAYSCALE, and cv2.IMREAD_UNCHANGED. Actually, this flag defines the mode in which the image should be read. NOTE: By default, the value of this flag parameter is cv2.IMREAD_COLOR or 1.

<b>cv2.imread()</b>
method loads an image from the specified file. If the image cannot be read (because of missing file, improper permissions, unsupported or invalid format) then this method returns an empty matrix.

<b>Syntax: cv2.imread(path, flag)</b>

<b>Parameters:</b> path: A string representing the path of the image to be read.
flag: It specifies the way in which image should be read. It’s default value is cv2.IMREAD_COLOR

<b>Return Value:</b> This method returns an image that is loaded from the specified file.

<b>cv2.IMREAD_COLOR: </b>It specifies to load a color image. Any transparency of image will be neglected. It is the default flag. Alternatively, we can pass integer value 1 for this flag.

<b>cv2.IMREAD_GRAYSCALE: </b>It specifies to load an image in grayscale mode. Alternatively, we can pass integer value 0 for this flag.
<b>cv2.IMREAD_UNCHANGED:</b> It specifies to load an image as such including alpha channel. Alternatively, we can pass integer value -1 for this flag.

In [13]:
print(img)

[[[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 ...

 [[ 60  18  84]
  [ 60  18  84]
  [ 58  27  92]
  ...
  [ 84  73 173]
  [ 76  68 172]
  [ 79  62 177]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]]


In [4]:
cv2.imshow("1 st image..", img)
cv2.waitKey()

-1

In [5]:
img.shape

(512, 512, 3)

<li><b>Height </b> represents the number of pixel rows in the image or the number of pixels in each column of the image array.
<li> <b>Width </b>represents the number of pixel columns in the image or the number of pixels in each row of the image array.
<li><b>Number of Channels</b> represents the number of components used to represent each pixel.

In [6]:
# height, width, number of channels in image
height = img.shape[0]
width = img.shape[1]
channels = img.shape[2]
channels

3

In [17]:
cv2.imshow('window 1 our section..', img)
cv2.waitKey()
#First argument is name of the window that is displayed when image is shown in.
#Second argument is the image to be shown in the window.

-1

<h3><font color='red'> OpenCV Python – Save Image</font></h3>


In [7]:
# Cropping an image
cropped_image = img[80:280, 150:330]
cv2.imwrite('newImage.png',cropped_image) ## take care of adding the extension of image
# the crooped img will be saved in the same path of current jupyter

True

where

<li><b>First Argument </b>is Path to the destination on file system, where image is ought to be saved.
<li><b>Second Argument</b> is ndarray containing image
<li><b>Returns</b> True is returned if the image is written to file system, else False.

In [9]:
cropped_image = img[80:280, 150:330]
cv2.imwrite('Desktop/new_Image.png',cropped_image)


True

In [ ]:
# Display cropped image
cv2.imshow("cropped", cropped_image)
cv2.waitKey()

<b>1.waitKey(0) </b>will display the window infinitely until any keypress (it is suitable for image display).

<b>2.waitKey(1)</b> will display a frame for 1 ms, after which display will be automatically closed. Since the OS has a minimum time between switching threads, the function will not wait exactly 1 ms, it will wait at least 1 ms, depending on what else is running on your computer at that time.

So, if you use waitKey(0) you see a still image until you actually press something while for waitKey(1) the function will show a frame for at least 1 ms only.

In [ ]:
cv2.destroyAllWindows() # destroys the window showing image

In [ ]:
cropped_image.shape

<h3><font color='red'> OpenCV Python – Resize image


<li><b>src</b>	[required] source/input image
<li><b>dsize</b>	[required] desired size for the output image
<li><b>fx</b>	[optional] scale factor along the horizontal axis
<li><b>fy</b>	[optional] scale factor along the vertical axis
<li><b>interpolation</b>	[optional] flag that takes one of the following methods. INTER_NEAREST – a nearest-neighbor interpolation INTER_LINEAR – a bilinear interpolation (used by default) INTER_AREA – resampling using pixel area relation. It may be a preferred method for image decimation, as it gives moire’-free results. But when the image is zoomed, it is similar to the INTER_NEAREST method. INTER_CUBIC – a bicubic interpolation over 4×4 pixel neighborhood INTER_LANCZOS4 – a Lanczos interpolation over 8×8 pixel neighborhood

Resizing an image can be done in many ways. We will look into examples demonstrating the following resize operations.

<li><b> 1- Preserve Aspect Ratio</b> (height to width ratio of image is preserved)
        <li><b> >>> 1-1 Downscale</b> (Decrease the size of the image)
        <li><b> >>> 1-2 Upscale </b>(Increase the size of the image)
<li><b>2- Do not preserve Aspect Ratio</b>
        <li><b>2-1 >>> Resize only the width </b>(Increase or decrease the width of the image keeping height unchanged)
        <li><b>2-2 >>> Resize only the height </b>(Increase or decrease the height of the image keeping width unchanged)
<li><b>3- Resize to specific width and height</b>

In [1]:
import cv2 
img = cv2.imread(r"C:\Users\Elhamd Pc\Pictures\Screenshots\Screenshot 2023-10-10 230514.png", cv2.IMREAD_UNCHANGED)
 
print('Original Dimensions : ',img.shape)
 
scale_percent = 60 # percent of original size
width = int(img.shape[1] * scale_percent / 100)
height = int(img.shape[0] * scale_percent / 100)
dim = (width, height)
  
# resize image
resized = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
 
print('Resized Dimensions : ',resized.shape)
cv2.imshow("Original image", img)
 
cv2.imshow("Resized image", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

Original Dimensions :  (571, 475, 4)
Resized Dimensions :  (342, 285, 4)


In [3]:
# let's start with the Imports 
import cv2
import numpy as np

# Read the image using imread function
image = cv2.imread('Desktop/1.png')
cv2.imshow('Original Image', image)

# let's downscale the image using new  width and height
down_width = 300
down_height = 200
down_points = (down_width, down_height)
resized_down = cv2.resize(image, down_points, interpolation= cv2.INTER_LINEAR)

# let's upscale the image using new  width and height
up_width = 600
up_height = 400
up_points = (up_width, up_height)
resized_up = cv2.resize(image, up_points, interpolation= cv2.INTER_LINEAR)

# Display images
cv2.imshow('Resized Down by defining height and width', resized_down)
cv2.waitKey()
cv2.imshow('Resized Up image by defining height and width', resized_up)
cv2.waitKey()

#press any key to close the windows
cv2.destroyAllWindows()

<li>It is important to keep in mind the original aspect ratio of the image (i.e. width by height), if you want to maintain the same in the resized image too.
<li>Reducing the size of an image will require resampling of the pixels. 
<li>Increasing the size of an image requires reconstruction of the image. This means you need to interpolate new pixels.